swagger: "2.0"
info:
  description: "业务对象管理后端 API 列表"
  version: "0.0.1"
  title: "BOMS API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "leechau@126.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.168.12.220:8080"
basePath: "/v2"
tags:
- name: "project"
  description: "项目管理"
- name: "directory"
  description: "文件夹管理"
- name: "model"
  description: "模型文件管理"
- name: "publish"
  description: "模型发布相关"
schemes:
- "http"

paths:
  /projects:
    get:
      tags:
      - "project"
      summary: "返回项目列表"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Meta'
            example:
              - id: 101
                name: 广东风电
                path: "proj1234"
                type: "project"
                created: "2017-10-12"
              - id: 102
                name: 国网财务分析
                path: "proj234"
                type: "project"
                created: "2017-10-12"
        405:
          description: "Invalid input"

    post:
      tags:
      - "project"
      summary: "新建项目"
      description: 新建项目
      operationId: "newProject"
      consumes:
      - "application/json"
      produces:
      - "text/plain"
      parameters:
      - name: "project"
        in: "body"
        description: "待创建项目内容"
        required: true
        schema:
          $ref: "#/definitions/Meta"
      responses:
        '201':
          description: 创建项目成功
        '400':
          description: 创建项目失败

  /projects/{id}:
    get:
      tags:
      - "project"
      summary: "获取指定项目内容"
      description: 获取项目内容
      operationId: ""
      produces:
      - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: 项目ID
          required: true
          type: "string"
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        '404':
          description: 项目不存在


    put:
      tags:
      - "project"
      summary: "修改项目名称"
      description: 更新项目内容
      operationId: ""
      produces:
      - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: 项目ID
          type: "string"
          required: true
        - name: "project"
          in: "body"
          description: "项目名称"
          required: true
          schema:
            type: string
            example: "风电项目"
      responses:
        '200':
          description: success

    delete:
      tags:
      - "project"
      summary: "删除项目"
      description: 删除项目
      operationId: ""
      produces:
      - "application/json"
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          type: "string"
      responses:
        '204':
          description: Project deleted
        '404':
          description: Project not found

  /projects/{id}/directory:
    post:
      tags:
      - "directory"
      summary: "新建项目目录"
      description: 新建项目目录
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          type: string
        - name: "project"
          in: "body"
          description: "项目内容"
          required: true
          schema:
            $ref: "#/definitions/Directory"
      responses:
         '201':
           description: 新建目录成功
         '400':
           description: 新建目录失败

  /projects/{pid}/directory/{did}:
    delete:
      tags:
      - "directory"
      summary: "删除项目目录"
      description: 删除项目目录
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          type: "string"
        - in: path
          name: did
          description: 目录ID
          required: true
          type: "string"
      responses:
        '204':
          description: directory deleted
        '404':
          description: directory not found

  /projects/{pid}/directory1/{did}:
    put:
      tags:
      - "directory"
      summary: "更新项目目录"
      description: 更新项目目录
      parameters:
        - in: path
          name: pid
          description: 项目ID
          type: string
          required: true
        - in: path
          name: did
          description: 项目路径ID
          type: string
          required: true
        - name: "project-content"
          in: "body"
          description: "项目内容"
          required: true
          schema:
            $ref: "#/definitions/Directory"
      responses:
        '201':
           description: updata success
        '400':
           description: updata failed

  /projects/{id}/dataobj:
    put:
      tags:
      - "publish"
      summary: "发布业务对象"
      description: 发布业务对象
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          type: string
      responses:
        '200':
          description: 发布业务对象成功
        '404':
          description: 项目不存在

  /projects/{id}/model:
    post:
      tags:
      - "model"
      summary: "新建模型文件"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of project"
        required: true
        type: "string"
      responses:
        201:
          description: "创建模型成功"
          schema:
            type: array
            items:
              $ref: "#/definitions/Meta"
            example:
              id: ""
              name: "模型名称"
              path: "d3/d4"
              nodetype: "model"
              created: "2017-10-12"
        400:
          description: "创建模型失败"

  /projects/{pid}/model/{mid}:
    delete:
      tags:
      - "model"
      summary: "删除模型文件"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pid"
        in: "path"
        description: "项目ID"
        required: true
        type: "string"
      - name: "mid"
        in: "path"
        description: "模型ID"
        required: true
        type: "string"
      responses:
          '204':
             description: 删除模型成功
          '404':
             description: 删除模型失败
    put:
      tags:
      - "model"
      summary: "更新模型内容"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pid"
        in: "path"
        description: "项目ID"
        required: true
        type: "string"
      - name: "mid"
        in: "path"
        description: "模型ID"
        required: true
        type: "string"
      responses:
        200:
          description: "更新成功"
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
            example:
              meta:
                id: 'model123'
                name: '模型名称'
                path: 'd3/d4'
                nodetype: 'model'
                created: '2017-10-12'
              raw: {}
              mdl: {}
              prop: {}
              con: {}
        400:
          description: "更新失败"

  /projects/{pid}/model/{mid}/bos:
    get:
      tags:
      - "model"
      summary: "返回模型包含的业务对象"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pid"
        in: "path"
        description: "项目ID"
        required: true
        type: "string"
      - name: "mid"
        in: "path"
        description: "模型ID"
        required: true
        type: "string"
      responses:
        200:
          description: "success"
          schema:
            type: array
            items:
              $ref: '#/definitions/BOs'
            example:
                id: 'model1123'
                mdl: []
        400:
          description: "failed"
  /projects/{pid}/model/{mid}/connections:
    get:
      tags:
      - "model"
      summary: "返回模型包含的关联关系"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pid"
        in: "path"
        description: "项目ID"
        required: true
        type: "string"
      - name: "mid"
        in: "path"
        description: "模型ID"
        required: true
        type: "string"
      responses:
        200:
          description: "success"
          schema:
            type: array
            items:
              $ref: '#/definitions/BOCon'
            example:
                id: 'model1123'
                mdl: []
        400:
          description: "failed"
  /projects/{pid}/model/{mid}/files:
    get:
      tags:
      - "model"
      summary: "返回模型文件内容"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "pid"
        in: "path"
        description: "项目ID"
        required: true
        type: "string"
      - name: "mid"
        in: "path"
        description: "模型ID"
        required: true
        type: "string"
      responses:
        200:
          description: "success"
          schema:
            type: array
            items:
              $ref: '#/definitions/ModelFiles'
            example:
                id: 'model1123'
                files:
                  - name: m1_id_model.json
                    content: ''
                  - name: m1_id_con.json
                    content: ''
                  - name: m1_id_prop.json
                    content: ''
        400:
          description: "failed"

definitions:
  Project:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 123
      name:
        type: string
        example: "safsd"
    required:
      - id
      - name

  Directory:
    type: object
    properties:
      name:
        type: string
        example: '业务对象2'
      path:
        type: string
        example: 'd3/d4'
    required:
      - name
      - path

  ModelFiles:
      type: object
      properties:
        id:
          type: string
        files:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              content:
                type: string
            required:
              - name
              - content
      required:
        - id
        - files

  Meta:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      path:
        type: string
      nodetype:
        type: string
      created:
        type: string

  Model:
    type: object
    properties:
      name:
        type: string
      path:
        type: string
    required:
      - name
      - path

  Node:
    type: object
    properties:
      meta:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          path:
            type: string
          nodetype:
            type: string
          created:
            type: string
        required:
          - id
          - name
          - path
          - nodetype
          - created
      raw:
        type: object
      mdl:
        type: object
      prop:
        type: object
      con:
        type: object
    required:
      - meta

  BOs:
      type: object
      properties:
        id:
          type: string
        mdl:
          type: object

  BOCon:
      type: object
      properties:
        id:
          type: string
        con:
          type: object

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
