openapi: '3.0.0'

info:
  title: BOMS API
  description: BOMS API Specification
  version: "0.1.3"

servers:
  - url: localhost:8080
    description: test server

paths:
  /projects:
    get:
      description: 返回项目列表
      responses:
        '200':
          description: success
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Project'
                example:
                  - id: 101
                    name: 广东风电
                  - id: 102
                    name: 国网财务分析

    post:
      description: 新建项目
      requestBody:
        description: 项目信息
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Project'
            example:
              $ref: '#/components/examples/project'
      responses:
        '201':
          description: 创建项目成功
        '400':
          description: 创建项目失败

  /projects/{id}:
    get:
      description: 获取项目内容
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
                example:
                  id: 'proj123'
                  nodes:
                    - id: "m1"
                      name: "模型1"
                      path: "d1/d2"
                      type: "model"
                    - id: "m2"
                      name: "模型2"
                      path: "d3"
                      type: "model"
                    - id: "d5"
                      name: "文件夹2"
                      path: "d3/d4"
                      type: "directory"
        '404':
          description: 项目不存在

    put:
      description: 更新项目内容
      parameters:
        - in: path
          name: id
          description: 项目ID
          schema:
            type: string
          required: true
      requestBody:
        description: 项目内容
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/BOI'
            example:
              raw: {}
              mdl: {}
              prop: {}
              con: {}
      responses:
        '200':
          description: success

    delete:
      description: 删除项目
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Project deleted
        '404':
          description: Project not found

  /projects/{id}/directory:
    post:
      description: 新建项目目录
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          schema:
            type: string
      requestBody:
        description: 新增信息
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Directory'
            example:
              $ref: '#/components/examples/directory'
      responses:
         '201':
           description: 新建目录成功
         '400':
           description: 新建目录失败

    delete:
      description: 删除项目目录
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          schema:
            type: string
        - in: path
          name: did
          description: 目录ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: directory deleted
        '404':
          description: directory not found

  /projects/{pid}/directory/{did}:
    put:
      description: 更新项目目录
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          schema:
            type: string
        - in: path
          name: did
          description: 目录ID
          required: true
          schema:
            type: string
      requestBody:
        description: 项目信息
        required: true
        content:
          'application/json':
            schema:
               $ref: '#/components/schemas/Directory'
            example:
               $ref: '#/components/examples/directory'
      responses:
        '200':
           description: updata success
        '400':
           description: updata failed

  /projects/{id}/dataobj:
    put:
      description: 发布业务对象
      parameters:
        - in: path
          name: id
          description: 项目ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 发布业务对象成功
        '404':
          description: 项目不存在

  /projects/{id}/model:
    post:
      description: 新建模型文件
      requestBody:
        description: 模型信息
        required: true
        content:
          'application/json':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Model'
              example:
                name: 模型名称
                path: d3/d4
      responses:
        '201':
          description: 模型创建成功
        '400':
          description: 模型创建失败

  /projects/{pid}/model/{mid}:
    delete:
        description: delete a model
        parameters:
          - in: path
            name: pid
            description: 项目ID
            required: true
            schema:
              type: string
          - in: path
            name: mid
            description: 模型ID
            required: true
            schema:
              type: string
        responses:
          '204':
             description: Model deleted
          '404':
             description: Model not found

    put:
      description: 更新模型内容
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          schema:
            type: string
        - in: path
          name: mid
          description: 模型ID
          required: true
          schema:
            type: string
      requestBody:
        description: 模型内容
        required: true
        content:
          'application/json':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ModelWithMeta'
              example:
                name: '模型名称'
                path: 'd3/d4'
                raw: {}
                mdl: {}
                prop: {}
                con: {}
      responses:
        '200':
          description: success
        '400':
          description: failed

  /projects/{pid}/model/{mid}/bos:
    get:
      description: 返回模型包含的业务对象
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          schema:
            type: string
        - in: path
          name: mid
          description: 模型ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BOs'
                example:
                  id: 'model1123'
                  mdl: []
        '400':
          description: failed

  /projects/{pid}/model/{mid}/connections:
    get:
      description: 返回模型包含的关联关系
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          schema:
            type: string
        - in: path
          name: mid
          description: 模型ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BOCon'
                example:
                  id: 'model1123'
                  con: []
        '400':
          description: failed

  /projects/{pid}/model/{mid}/files:
    get:
      description: 返回模型文件内容
      parameters:
        - in: path
          name: pid
          description: 项目ID
          required: true
          schema:
            type: string
        - in: path
          name: mid
          description: 模型ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelFiles'
                example:
                  id: 'model1123'
                  files:
                    - name: m1_id_model.json
                      content: ''
                    - name: m1_id_con.json
                      content: ''
                    - name: m1_id_prop.json
                      content: ''
        '400':
          description: failed

components:
  examples:
    project:
      value:
        id: 123
        name: '广东风电'
      summary: A demo project

    directory:
      value:
        name: "业务对象2"
        path: "d3/d4"

  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name

    ModelFiles:
      type: object
      properties:
        id:
          type: string
        files:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              content:
                type: string
            required:
              - name
              - content
      required:
        - id
        - files

    Model:
      type: object
      properties:
        name:
          type: string
        path:
          type: string
      required:
        - name
        - path

    BOs:
      type: object
      properties:
        id:
          type: string
        mdl:
          type: object

    BOCon:
      type: object
      properties:
        id:
          type: string
        con:
          type: object
        
    BOI:
      type: object
      properties:
        raw:
          type: object
        mdl:
          type: object
        prop:
          type: object
        con:
          type: object
      required:
        - raw
        - mdl
        - prop
        - con

    ModelWithMeta:
        type: object
        properties:
          name:
            type: string
          path:
            type: string
          raw:
            type: object
          mdl:
            type: object
          prop:
            type: object
          con:
            type: object
        required:
        - name
        - path
        - raw
        - mdl
        - prop
        - con

    Directory:
      type: object
      properties:
        name:
          type: string
        path:
          type: string
      required:
        - name
        - path

    Node:
      type: object
      properties:
        id:
          type: string
        nodes:
          type: array
          items:
            type: object
            properties:
             id:
              type: string
             name:
              type: string
             path:
              type: string
             type:
              type: string
            required:
              - id
              - name
              - path
              - type
      required:
        - id
        - nodes
